### ISSUE TITLE
releases中的exe文件不可用

### ISSUE THREAD

**Issue by shadow-aaa** [liuzhijie443/duifene_auto_sign#1]
直接运行py文件可以正常使用，运行exe文件会报错，execute script failed : 1，似乎是这个提示

**Comment by bytehola** [comment]
> 直接运行py文件可以正常使用，运行exe文件会报错，execute script failed : 1，似乎是这个提示

pyinstaller打包的，如果运行不了自己用机器打包一遍。

**Comment by shadow-aaa** [comment]
我尝试了，成功运行了
